# Generated by Django 4.2.7 on 2024-03-14 00:02

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buser", "0003_merge_20240313_2102"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buser",
            name="followers",
        ),
        migrations.RemoveField(
            model_name="buser",
            name="following",
        ),
        migrations.AlterField(
            model_name="buser",
            name="description",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="buser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="buser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="buser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="buser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
